### ISSUE TITLE
No images in folder "images"

### ISSUE THREAD

**Issue by kuniks** [LAK132/SourceExplorer#48] opened 2021-02-09 19:04 UTC
# IMPORTANT
Please provide a copy of the Error Log (File -> Save Error Log...) or the Crash Log ("SEND-THIS-CRASH-LOG-TO-LAK132.txt") uploaded to https://pastebin.com . Without this we cannot/will not help you! 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

[SEND-THIS-CRASH-LOG-TO-LAK132.txt](https://github.com/LAK132/SourceExplorer/files/5953692/SEND-THIS-CRASH-LOG-TO-LAK132.txt)
Game: https://gamejolt.com/games/toonys_classic/462444 (Six Horrors 4 Cancelled Build)

**Comment by LAK132** [comment] 2021-05-30 06:59
Duplicate of #43

**Closed by LAK132** 2021-05-30 06:59 UTC
Labels: 292, bug
