### ISSUE TITLE
Can't dump Jollibee's phase 2

### ISSUE THREAD

**Issue by AGK89** [LAK132/SourceExplorer#49] opened 2021-03-06 21:17 UTC
THE DEBUG LOG
https://pastebin.com/DpbDBDX4

**Describe the bug**
I open Jollibee's Phase 2 with auto dump enabled, wait for SE to finish dumping 
and I get EVERYTHING... except the images. :( it even creates an image folder.
I think IvanG made Jollibee's phase 2 in CTF2.5+ (with the plus DLC)
breaking the SE from extracting the images.

Please Update the App to support 2.5+.

**To Reproduce**
1. Open Source Explorer
2. Enable auto-dump
3. Open Jollibee's Phase 2.exe
4. Wait...
5. Look in image folder (contains absolutely nothing)
6. Save error log
7.Send the issue

**Expected behavior**
All I wanted to do was to dump and peek at the textures and sounds
so I expected Jollibee's Phase 2 to dump everything.

**Screenshots**

**Additional context**
Even Texmod can dump the Phase 2 Textures but they are not
transparent and are hard to get.

It can dump the demo version of Jollibee's 1 at least.

![Images folder](https://user-images.githubusercontent.com/80176555/110220969-305b2680-7ec1-11eb-84cd-db1a2ec6c68d.PNG)

![Sounds folder](https://user-images.githubusercontent.com/80176555/110220975-394bf800-7ec1-11eb-96a8-9b20a1e68e85.PNG)

**Comment by LAK132** [comment] 2021-06-02 13:18
Duplicate of #43

**Closed by LAK132** 2021-06-02 13:18 UTC
Labels: 292, bug
