### ISSUE TITLE
Fix to make it dump images for Clickteam Fusion 2.5+

### ISSUE THREAD

**Issue by The-Panda-Man-8108** [LAK132/SourceExplorer#42] opened 2020-12-11 14:38 UTC
# IMPORTANT
Please provide a copy of the Error Log (File -> Save Error Log...) or the Crash Log ("SEND-THIS-CRASH-LOG-TO-LAK132.txt") uploaded to https://pastebin.com . Without this we cannot/will not help you! 

**Describe the bug**
It does not dump the images of a Clickteam Fusion 2.5+ game. It does dump the sounds, not the images.

**To Reproduce**
Try to dump the images of a clickteam 2.5+ game.

**Expected behavior**
Wanted to dump the files of my selected game.

**Screenshots**
No screenshots. Its self explanatory.

**Additional context**
The program needs to be updated to dump 2.5+

**Comment by LAK132** [comment] 2020-12-13 04:55
Closing because you didn't provide the error log.

**Closed by LAK132** 2020-12-13 04:55 UTC
Labels: bug

**Comment by LAK132** [comment] 2021-06-02 12:45
Assuming duplicate of #43
