### ISSUE TITLE
Error when extracting The Return to Freddy's Files

### ISSUE THREAD

**Issue by JamesSmith123445** [LAK132/SourceExplorer#50] opened 2021-03-22 23:25 UTC
[SEND-THIS-CRASH-LOG-TO-LAK132.txt](https://github.com/LAK132/SourceExplorer/files/6185840/SEND-THIS-CRASH-LOG-TO-LAK132.txt)

**Describe the bug**
The bug when extract is new Image Bank!

**To Reproduce**
1. Go to ''

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LAK132** [comment] 2021-06-02 13:17
Duplicate of #43

**Closed by LAK132** 2021-06-02 13:17 UTC
Labels: 283, bug
