### ISSUE TITLE
Not dumping 2.5+ images

### ISSUE THREAD

**Issue by ahaijka56** [LAK132/SourceExplorer#52] opened 2021-06-02 10:40 UTC
I tried to dump files of sonicallstars.exe but program dumped only sounds,icon,and effects

Log:
[allstars.txt](https://github.com/LAK132/SourceExplorer/files/6583827/allstars.txt)

**Comment by LAK132** [comment] 2021-06-02 11:07
Was this using the latest stable release or did you build SE yourself?

**Comment by ahaijka56** [comment] 2021-06-02 11:35
latest relase

**Comment by ahaijka56** [comment] 2021-06-02 12:37
i downloaded 2.0 but program crashes

**Comment by LAK132** [comment] 2021-06-02 12:42
In that case this is a duplicate of #43

**Closed by LAK132** 2021-06-02 12:42 UTC
Labels: bug
